name             'wsus-server'
maintainer       'Criteo'
maintainer_email 'b.courtois@criteo.com'
license          'Apache-2.0'
description      'Installs wsus server'
version          '2.3.2'
supports         'windows'
depends          'windows'

chef_version '>= 13.0'
source_url 'https://github.com/criteo-cookbooks/wsus-server'
issues_url 'https://github.com/criteo-cookbooks/wsus-server/issues'
