# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
require 'chefspec'
require 'chefspec/policyfile'

WINDOWS_2016_OHAI = { platform: 'windows', version: '2016' }.freeze
WINDOWS_2019_OHAI = { platform: 'windows', version: '2019' }.freeze
LINUX_OHAI = { platform: 'centos', version: '8' }.freeze

def custom_chef_run(ohais = {}, attributes = {})
  # Mock file_cache_path
  allow(Chef::Config).to receive(:[]).and_call_original
  allow(Chef::Config).to receive(:[]).with('file_cache_path').and_return('')
  ChefSpec::SoloRunner.new(ohais) do |node|
    node.override.merge!(attributes)
  end.converge(described_recipe)
end

def windows2016_chef_run(attributes = {})
  custom_chef_run(WINDOWS_2016_OHAI, attributes)
end

def windows2019_chef_run(attributes = {})
  custom_chef_run(WINDOWS_2019_OHAI, attributes)
end

def linux_chef_run(attributes = {})
  custom_chef_run(LINUX_OHAI, attributes)
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
end
