# This is a basic workflow to help you get started with Actions
name: Criteo Cookbooks CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  supermarket:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Publish to supermarket
      uses: afaundez/chef-supermarket-action@8cdbe1cccbe1ecd8685b2ea8f48780135bae7cee
      with:
        user: criteo
        cookbook: wsus-server
        category: Package Management
      env:
        SUPERMARKET_API_KEY: ${{ secrets.SUPERMARKET_API_KEY }}
